package edu.orangecoastcollege.view;



import edu.orangecoastcollege.controller.Controller;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;

public class SignInScene {
    private static Controller controller = Controller.getInstance();


	@FXML
	private Label emailErrorLabel;
	@FXML
	private Label passwordErrorLabel;
	@FXML
	private TextField emailAddressTF;
	@FXML
	private TextField passwordTF;
	@FXML
	private Label signInErrorLabel;

	// Event Listener on Label.onMouseClicked
	@FXML
	public void loadSignUp(MouseEvent event) {
	    ViewNavigator.loadScene("Sign Up", ViewNavigator.SIGN_UP_SCENE);
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public boolean signin(ActionEvent event) {
		// TODO Autogenerated
	    String email = emailAddressTF.getText();
	    String password = passwordTF.getText();
	    //Let's check to see if the error labels should be made visible
	    emailErrorLabel.setVisible(email.isEmpty());
	    passwordErrorLabel.setVisible(password.isEmpty());

	    //If either one is visible, return false
	    if (emailErrorLabel.isVisible() || passwordErrorLabel.isVisible())
	        return false;

	    //Let's try to sign the user in
	    String result = controller.signInUser(email, password);

	    
	    
        return true;


	}

//	@FXML
//	public boolean signIn() {
//	    // Let's read information from the user
//	    String email = emailAddressTF.getText();
//	    String password = passwordTF.getText();
//
//	    // Let's check to see if the error labels should be made visible:
//	    emailErrorLabel.setVisible(email.isEmpty());
//	    passwordErrorLabel.setVisible(password.isEmpty());
//
//	    // If either one is visible, return false
//	    if (emailErrorLabel.isVisible() || passwordErrorLabel.isVisible())
//	        return false;
//
//	    // Let's try to sign the user in (store the result)
//	    String result = controller.signInUser(email, password);
//	    if (result.equalsIgnoreCase("SUCCESS")) {
//			signInErrorLabel.setVisible(false);
//			ViewNavigator.loadScene("User Information", ViewNavigator.USER_INFORMATION_SCENE);
//			return true;
//		}
//		signInErrorLabel.setText(result);
//		signInErrorLabel.setVisible(true);
//		return false;
//	}
//
//	@FXML
//	public void loadSignUp(MouseEvent event)
//	{
//	    ViewNavigator.loadScene("Sign Up", ViewNavigator.SIGN_UP_SCENE);
//	}

}
